### ISSUE TITLE
Docker host with port will break the script.

### ISSUE THREAD

**Issue by brycereitano** [silinternational/ecs-deploy#1]
When running the command with the `-i` tag (which is required.) while supplying the port on the docker host will result in.

```
docker run --rm --env-file=./.aws.env silintl/ecs-deploy -c my-app-cluster -n MyAppServer -i example.com:5000/my-app:latest
Current task definition: <irrelevant information>
You must specify an image with a tag
```

Which won't allow me too use this tool with the current configuration I have with my docker host.

I am currently investigating my own fix.

**Comment by fillup** [comment]
@brycereitano, I just merged the fix for this into master and Docker hub is rebuilding the image. Thank you for reporting the issue and providing the PR!
