### ISSUE TITLE
Please support it can designate TASK_DEFINITION_ARN

### ISSUE THREAD

**Issue by ww24** [silinternational/ecs-deploy#108]
I want to designate TASK_DEFINITION_ARN when I use latest task definition and update ecs service.
Because `getCurrentTaskDefinition` function does not get latest task definition.

Ex.
```
ecs-deploy -c $cluster_name -n $service_name --task-definition-arn $task_definition_arn -i $image
```

How to get last task definition:
```
LAST_TASK_DEFINITION_ARN=$(aws ecs list-task-definitions --status ACTIVE --family-prefix "${FAMILY_PREFIX}" --sort DESC | jq -r ".taskDefinitionArns[0]")
```

**Comment by abelboldu** [comment]
+1
I would be nice to have a parameter to use either the last task definition or a provided json task file

**Comment by devon-sil** [comment]
#109 has the final comment mentioning it should be implemented.
