### ISSUE TITLE
[Feature Request] Support for bounce/restart deployment

### ISSUE THREAD

**Issue by amit1rrr** [silinternational/ecs-deploy#113]
Hey, 
Is it possible using ecs-deploy to just redeploy the most recent task definition on the service?

This is useful if you just want to reboot the fleet. In my case, I am using same task definition on 2 services and running ecs-deploy creates separate (but identical) task definition for both. I would like to run ecs-deploy on first service which will create a new task definition and just run ecs-deploy with bounce type of parameter which will update the second service to most recent version.

**Comment by fillup** [comment]
Hi @amit1rrr this was just merged in with the new `--force-new-deployment` flag in #141.
