### ISSUE TITLE
Support for ECS scheduled tasks 

### ISSUE THREAD

**Issue by trntv** [silinternational/ecs-deploy#122]
It would be awesome to add support for scheduled rules to update their targets on task's revision creation.
http://docs.aws.amazon.com/cli/latest/reference/events/put-targets.html

**Comment by gillisd** [comment]
@trntv It's a bit hacky, but you can make ecs-deploy work by doing the following:

1. Create a dummy service that uses the task definition that you want to run in your scheduled tasks. Set the number of tasks to run equal to 0.
2. Make sure your scheduled tasks don't specify a version number for their task definition.
3. Deploy to the dummy service

**Comment by fillup** [comment]
Sounds like there is a solution/workaround that can be used. If there is something that can be done to add better support for them I'm open to suggestions and pull requests.

**Comment by andy-plutoflume** [comment]
FWIW we're using https://github.com/fabfuel/ecs-deploy/pull/58

**Comment by fillup** [comment]
I just pulled in a PR and released it, #150, does that do what you're looking for?
