### ISSUE TITLE
Support for Fargate Task Definitions

### ISSUE THREAD

**Issue by lcsmontiel** [silinternational/ecs-deploy#127]
Yesterday AWS launched the fargate launch type and the current ecs-deploy version can't create fargate task definitions.

**Comment by lcsmontiel** [comment]
https://medium.com/containers-on-aws/say-hello-to-amazon-fargate-and-amazon-elastic-container-service-for-kubernetes-66707dd14976

**Comment by kakakakakku** [comment]
I tried Fargate support / https://github.com/silinternational/ecs-deploy/pull/129

**Comment by kakakakakku** [comment]
@fillup 
I contributed supporting Fargate via https://github.com/silinternational/ecs-deploy/pull/129.
So, we can close it 👍

**Comment by fillup** [comment]
Fixed in #129
