### ISSUE TITLE
Bug with parameter 'placementConstraints' on register task definition

### ISSUE THREAD

**Issue by robsoncompuff** [silinternational/ecs-deploy#131]
I found a bug to register the new task definition, my current task definition does not have 'placementConstraints', in this case I checked the last commit 824f848676bf2477bdefc641214fd55d82746c9f that the default value in ecs-deploy for this parameter is null if it is not filled, I checked the documentation aws null is not a valid value for this parameter, it should be an empty array.

**Comment by fillup** [comment]
I believe this is a known issue with older task definitions. In adding Fargate support I found the same problem with some of my older services, see comment https://github.com/silinternational/ecs-deploy/pull/129#issuecomment-372874142. The quick fix is to create a new revision of the task definition from the AWS console without making any changes and then `ecs-deploy` can work fine with it.
