### ISSUE TITLE
Feature request: Implement forceNewDeployment of ECS task upon deployment option

### ISSUE THREAD

**Issue by sterichards** [silinternational/ecs-deploy#137]
I hope you don't mind a feature request being placed here

I'm finding it tedious to manually stop an ECS task once i've ran ecs-deploy to stop the predecessor. awscli offers a parameter to force a new deployment as seen here - https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#API_UpdateService_RequestSyntax

Having this feature within silinternational/ecs-depoy would be very welcome

If there is no response within 5 days to this I shall fork code and attempt the change myself

Thank you,

**Comment by fillup** [comment]
Thank you for the suggestion, I'll get to reviewing and merging the existing PR as soon as I can.

**Comment by fillup** [comment]
Thanks to @kakakakakku this has been implemented and released in version `3.5.0`
