### ISSUE TITLE
Unable to describe task definition

### ISSUE THREAD

**Issue by metrue** [silinternational/ecs-deploy#145]
Hi there.

Am I missing something ? I got `An error occurred (ClientException) when calling the DescribeTaskDefinition operation: Unable to describe task definition.`

when I ran
```
./ecs-deploy -n pong -i xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/pong:latest -r us-west-1 -c ca-staging-cluster
```

**Comment by Baggerone** [comment]
I don't really know what you need but have an idea in case no one else gets back to you.
Have you set the correct IAM Policy Configuration?

**Comment by metrue** [comment]
@Baggerone 

sorry for the unclear description here, will update it soon.

**Comment by jakubczaplicki** [comment]
Hi @metrue , I got the same error message that started to appear just recently. I wonder if AWS have changed something on their side. Last time I successfully deployed the code was 3 days ago, so the change would have to be fresh. The `ecs-deploy` haven't changed in 3 months.

**Comment by jakubczaplicki** [comment]
@metrue : make sure the service name is correct in the CLI:  `./ecs_deploy -c <cluster_name> -n <service_name> -i <registry> -r <region>`

**Comment by fillup** [comment]
I've only seen this error when I have a typo in either the cluster name or service name. Please reopen with more details if you are sure you have those set correctly.

**Comment by rajacsp** [comment]
> I've only seen this error when I have a typo in either the cluster name or service name. Please reopen with more details if you are sure you have those set correctly.

You saved my time by guessing my mistake right! I made a typo while creating a def.
