### ISSUE TITLE
Increase draining speed of tasks

### ISSUE THREAD

**Issue by Kostanos** [silinternational/ecs-deploy#147]
I have auto-deploy configured, which waits until tasks comes to normal state.
The long time of draining makes auto-deploy last longer then expected.

Can we add new feature to insure faster draining?
For example:
autoDrainingTimeout: 20s
killOnDrainingnTimeout: true

In this case, script will wait 20 s until auto draining completes, and if it will not be completed, the old tasks will be killed/or not, according to killOnDrainingnTimeout

**Comment by fillup** [comment]
@Kostanos thanks for the suggestion, but the draining timeout is already configurable by you with your load balancer. Also you can increase the timeout of `ecs-deploy` with the `-t` flag if you need more time for draining and deployment to complete.

**Comment by Kostanos** [comment]
how do you configure draining timeout in ALB (could not found it yet)?
this is exactly what I'm using -t, but making -t too big, makes deploy script last longer, which become cost inefficient if you use 3rd party pipelines like bitbucket.

**Comment by mewins-iwin** [comment]
For ALBs this looks like what you are after... 
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html#deregistration-delay
