### ISSUE TITLE
Not working once image repository name changed.

### ISSUE THREAD

**Issue by sagar-babar** [silinternational/ecs-deploy#162]
Hi,

I was just deploying my service with another image repository, and it took same old image.

It should need to give error/warning in case of image repository modification instead of saying successfully deployed new task definition.

Thanks,
Sagar

**Comment by mhvelplund** [comment]
I ran into this too. The "sed" search&replace for updating the image assumes that the repo hasn'et changed. If it has, then the search and replace statements don't match, and the image isn't replaced.

**Comment by mhuebner** [comment]
Also experiencing this issue! Just wondered why the image always stays the old one. Console output is different from what really happens!

**Comment by luisamador** [comment]
Just hit this issue too.

**Comment by unfor19** [comment]
I wish I had seen it before wasting 3 hours

**Comment by hybmg57** [comment]
any update here?

**Comment by unfor19** [comment]
I've created a PR that fixes it - https://github.com/silinternational/ecs-deploy/pull/204

If you need it ASAP - https://github.com/unfor19/ecs-deploy
If you need drone-ecs-deploy plugin (based on ☝️) - https://hub.docker.com/r/unfor19/drone-ecs-deploy
