### ISSUE TITLE
Secretsmanager secrets are getting lost due to an old version of AWS CLI

### ISSUE THREAD

**Issue by pioneer2k** [silinternational/ecs-deploy#180]
With the current image of ecs-deploy on hub.docker.com the Secretsmanager secret are getting lost when ecs-deploy creates a new task definition.
With local tests I found out that it has something to do with the version of the AWS CLI. With current versions there is no problem. 
Maybe someone can build a new image based on the current Dockerfile an push it to the registry?

**Comment by thisismana** [comment]
What @pioneer2k  mentioned plus the fact that the `executionRoleArn` is lost somewhere in the process:

<details>
An error occurred (ClientException) when calling the RegisterTaskDefinition operation: When you are specifying container secrets, you must also specify a value for 'executionRoleArn'.
</details>

**Comment by smuryginim** [comment]
resolved after `pip install boto3 --upgrade`

**Comment by AlejandroSilva** [comment]
Hi, i've got the same problem, already updated 'boto3' but keeps losing the `executionRoleArn`

the version of my cli is:
`aws-cli/1.16.155 Python/2.7.10 Darwin/17.7.0 botocore/1.12.145`

**Comment by fillup** [comment]
This should be fixed in the release today, version 3.7.0 which fixes the executionRoleArn loss.
