### ISSUE TITLE
ERROR: New task definition not running within 90 seconds

### ISSUE THREAD

**Issue by thesciz** [silinternational/ecs-deploy#184]
Running in Travis-CI. Everything works, the new container spins up and the old one spins down (after a few minutes), but the deploy task times out after 90 seconds surfacing the error noted in the title. 

Is there a way to fire-and-forget, or, alternatively, recognize that all is well? I've included my command line arguments below:

`ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:latest`

**Comment by manuca** [comment]
Same issue over here, I extended the timeout and I still have the issue. The deploy is working fine but for some reason it does not detect that the service was updated correctly.

**Comment by thesciz** [comment]
So I've increased the timeout to 10 minutes and that seems to be long enough to have everything shake out. I've spoken to AWS support and they told me that these delays are a known issue they hope to address, but didn't give me an ETA. The sticking points are that when you register a new target on your NLB, it should take 60-90 seconds to complete; same with deregistration, so you're at up to 3 minutes on these alone, plus any health check grace periods and health checks (minimum of 2). 

Really, the default timeout should be much longer ;)

**Comment by fillup** [comment]
Hi there, you can either increase your timeout based on what is normal for your service, or if you don't care to wait you can use the `--skip-deployments-check` flag.

**Comment by wolfgang-werner** [comment]
@fillup I had the same problem. I think the problem is, that the --skip-deployments-check flag only skips 'waitForGreenDeployment' - inside the updateService function the timeout is always used.

**Comment by wolfgang-werner** [comment]
@fillup One more thing: Thanks for the script, had helped me a lot! I learned that it is not possible to use --profile and --aws-assume-role together.
