### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by lukaspour** [silinternational/ecs-deploy#185]
Hi @fillup , thank you for this great project, I am just wandering if continue still maintain it as there is a bunch of PRs/issues and the last release was in August last year.

If you have a lack of time somebody could be set as a new maintainer. Thank you very much.

**Comment by fillup** [comment]
@lukaspour thanks for checking. the project is not dead, however maintaining it and reviewing new feature requests has been low on priorities lately. The script continues to work perfectly for me so it's hard to get in there and review and test features I don't need and wont use. I've been thinking recently about deciding on some standard for what kind of PRs we'll accept to scope it down and make it easier to review them. For example we don't need complex niche business rule capabilities, but when new features are added to ECS or the API changes in a way that we need to update the process of creating new task definitions, we'd certainly want that. I'm open to brining on a another maintainer but I think some standards about what we'd accept and not would be needed first.

**Comment by kakakakakku** [comment]
👏

**Comment by theintz** [comment]
Would you consider giving merge permissions to a second maintainer? Some issues have very simple working fixes in the PRs already, but haven't been merged for months.

**Comment by fillup** [comment]
@theintz yes, I'm open to that and have reached out to a common contributor to see if they are interested before I ask generally. This week I was able to merge in several valuable PRs and fix a couple issues so I'm going to close this issue for now.
