### ISSUE TITLE
Rollback on unhealth container

### ISSUE THREAD

**Issue by wcoc** [silinternational/ecs-deploy#187]
Hello guys,

I was thinking about rollback task version when container status is unhealthy after new version deploy.
How about waiting container stay health, to be successful deploy ?

Somebody has that kind of problem?

Maybe i can help to do...

What do you thing?

**Comment by fillup** [comment]
Hi @wcoc, does the `--enable-rollback` flag/feature not do what you're looking for?

**Comment by wcoc** [comment]
Hello @fillup, I think no, because the --enabel-rollback don't see if the task is HEALTHY, only see if the service deploy was finished.

I had a few problems in my tests, when I deployed a unhealthy container, and ecs-deploy updated my service with the new task revision, and it finished with successfully, but my container was running unhealthy.

and then i had a BIG problem, ecs service was killing and living, killing and living my task for ever.

Maybe a solution, be in ecs-deploy script, we search if all task were HEALTHY, if didn't, we rollback it.

What do you think about it?

**Comment by vpaul-dev** [comment]
Hello @fillup,
I just found this issue after running into a very similar situation, but I found that the changes in #200 do not work as expected when the tasks reach an "**UNHEALTHY**" **healthStatus**, and the deploy is marked as successful.
Here's the relevant part of a verbose run:
```
++ grep -e HEALTHY
+ RUNNING='"UNHEALTHY"'
+ '[' '"UNHEALTHY"' ']'
+ echo 'Service updated successfully, new task definition running.'
```

**Comment by devon-sil** [comment]
Appears #200 and #256 resolve this.
