### ISSUE TITLE
Error registering Task Definition with private repository authentication 

### ISSUE THREAD

**Issue by dchuiko** [silinternational/ecs-deploy#188]
If target task definition has private repository authentication script failures with the following error: 

`
An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Private repository authentication requires that the task definition specify a value for executionRoleArn.
`

To this this problem `executionRoleArn` should be copied from the source definition here: 
`CONDITIONAL_OPTIONS=(networkMode taskRoleArn executionRoleArn placementConstraints)`

**Comment by theintz** [comment]
This is a duplicate of #186 .
