### ISSUE TITLE
--aws-instance-profile is not yet in use

### ISSUE THREAD

**Issue by davidshare** [silinternational/ecs-deploy#218]
I keep getting this error when trying to deploy to ecs via gitlab ci

`--aws-instance-profile is not yet in use`

This is the anchor I use for the deployment

```
.deploy: &deploy_to_ecr
  image:
    name: silintl/ecs-deploy:latest
    entrypoint: [""]
  stage: deploy
  script:
    - /ecs-deploy --cluster $CI_AWS_ECS_CLUSTER --service-name $CI_AWS_ECS_SERVICE
      --aws-instance-profile arn:aws:iam::668089922344:instance-profile/app-graph-gitlab-runner-role
      --image $ECR:$CI_COMMIT_SHORT_SHA
      --region us-west-2
      --verbose
  when: manual
  ```
  
  This is how it is used.
  ```
deploy finance:
  variables:
    <<: *deploy-variables
    CI_AWS_ECS_SERVICE: app-test-appname
    ECR: 178353947583.dkr.ecr.us-west-2.amazonaws.com/hyre-finance-ecr
  <<: *deploy_to_ecr
```

Any help will be appreciated.

**Comment by fillup** [comment]
Hi @davidshare, well this is interesting, from the best I can tell that argument is essentially ignored. It prints out the message that it's not yet in use and then isn't used again. I can't remember at all why it exists and wasn't implemented. 

What is it you're ultimately trying to accomplish? I can try to look into how to support it and see if we can add or implement the arguments needed.

**Comment by devon-sil** [comment]
No response, closing.
