### ISSUE TITLE
Broken on Alpine Linux (busybox)

### ISSUE THREAD

**Issue by jangrewe** [silinternational/ecs-deploy#23]
I've been this script (big thanks, btw!) inside a Ubuntu-based Docker container for deployment, but recently switched to an Alpine-based and it doesn't work in there.

```
A client error (InvalidParameterException) occurred when calling the DescribeTasks operation: taskId longer than 36.
xargs: /usr/bin/aws: exited with status 255; aborting
```
I've checked the output of the commands and it seems to be double quotes around the Task ARNs:

```
aws --output json ecs --region eu-west-1 list-tasks --cluster MyCluster --service-name MyService --desired-status RUNNING | jq '.taskArns[]' | xargs '-I{}' echo '{}'
"arn:aws:ecs:eu-west-1:803064921768:task/4485a855-0608-4c75-bfd4-04e45fc7f34c"
"arn:aws:ecs:eu-west-1:803064921768:task/fcc976a2-2fa5-4e75-8d01-4f915a014342"
```
but it works fine with the "-r" switch for jq:
```
aws --output json ecs --region eu-west-1 list-tasks --cluster MyCluster --service-name MyService --desired-status RUNNING | jq -r '.taskArns[]' | xargs '-I{}' echo '{}'
arn:aws:ecs:eu-west-1:803064921768:task/4485a855-0608-4c75-bfd4-04e45fc7f34c
arn:aws:ecs:eu-west-1:803064921768:task/fcc976a2-2fa5-4e75-8d01-4f915a014342
```

Just saw issue #18 , this is probably related ;-)

**Comment by fillup** [comment]
@jangrewe thanks for the info, with Docker adopting Alpine I've been wanting to check it out too. I just merged in PR #25 of yours, let me know if that fixes it.

**Comment by jangrewe** [comment]
Tested and confirmed working! =)

PS: Alpine is great, i haven't had any issues migrating our images.

**Comment by fillup** [comment]
Awesome, thanks!
