### ISSUE TITLE
reset proxyConfiguration after deployment

### ISSUE THREAD

**Issue by ghost** [silinternational/ecs-deploy#236]
heyja,

We are using this script and noticed, that the proxyConfiguration gets deleted once we deploy a new task revision.
Currently we are using envoy as a side-car container and need to have the proxyConfiguration in place in order to be able to integrate the service into the AWS-Mesh.

cheers,
Aven

**Comment by mauritz-lovgren** [comment]
Yes, and the `"name": "ecs.capability.aws-appmesh"` is removed from `requiresAttributes` section in the resulting task definition as well.

**Comment by forevermatt** [comment]
> heyja,
> 
> We are using this script and noticed, that the proxyConfiguration gets deleted once we deploy a new task revision. Currently we are using envoy as a side-car container and need to have the proxyConfiguration in place in order to be able to integrate the service into the AWS-Mesh.
> 
> cheers, Aven

Hi @avendretter. It looks like `proxyConfiguration` may simply need to be added to [this line](https://github.com/silinternational/ecs-deploy/blob/5a6ee2f265f30e3e1615a67f2bfb8c142ebc9ad3/ecs-deploy#L378) in ecs-deploy (based on the [AWS docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html)). Can you test that to confirm whether it fixes the issue for you?

**Comment by forevermatt** [comment]
> Yes, and the `"name": "ecs.capability.aws-appmesh"` is removed from `requiresAttributes` section in the resulting task definition as well.

@mauritz-lovgren That sounds like it's probably a different issue. Would you mind submitting a new GitHub issue (and/or pull request) about that, to help us avoid losing track of your request when this issue is resolved?
