### ISSUE TITLE
Run task Github actions input not used

### ISSUE THREAD

**Issue by vpaul-dev** [silinternational/ecs-deploy#268]
Hello! I wanted to use the `--run-task` argument in a github action step but while configuring I found that the corresponding input, `run_task` (https://github.com/silinternational/ecs-deploy/blob/develop/action.yml#L103) is not used in the args list.

**Comment by forevermatt** [comment]
Thanks! Fixed in #272

**Comment by vpaul-dev** [comment]
Welcome! Thank you for integrating it!
