### ISSUE TITLE
ERROR: was unable to place a task. Reason: Capacity is unavailable at this time. Please try again later or in a different availability zone

### ISSUE THREAD

**Issue by pawan-1999** [silinternational/ecs-deploy#277]
Hi Team,

We are facing this issue multiple times. We have a subnet with available IPs but still getting this error again. I know if we keep multiple subnets with different available zones it can be fixed. but the above error or event is not logged in the AWS ECS service. If someone can add input on this will be helpful.

ecs-deploy, version 1.11.2
AWS ECS Platform version LATEST(1.4.0)
ECS Fargate 

Thanks & Regards
 Pawan Gupta

**Comment by devon-sil** [comment]
@pawan-1999 After reading the title of your issue here, this appears like a message being returned from AWS and not something ecs-deploy is likely able to resolve.  I recommend doing an internet search or searching https://repost.aws/ for some helpful answers.
