### ISSUE TITLE
Merge of name parsing broke

### ISSUE THREAD

**Issue by sriney-boc** [silinternational/ecs-deploy#29]
https://github.com/silinternational/ecs-deploy/commit/67238d9a81d354bda17050e64578ef5bb8b2f58b

No tags on the docker images so that when we pull latest, we got the latest code.

I can fork and manage our own docker images, but thought this issue should be looked at.

Unable to find image 'silintl/ecs-deploy:latest' locally
latest: Pulling from silintl/ecs-deploy
Status: Downloaded newer image for silintl/ecs-deploy:latest
Unable to parse image name: 357801675085.dkr.ecr.us-east-1.amazonaws.com/boc-staging-hcp:20160323183016-8b06035, check the format and try again
{
   "imageIds": [
       {
           "imageDigest": "sha256:7fe040d305f6d3ad9ceb7cd46908ce3b74cfeb995c4bfa158baf84ebc4b2731c"
       },
       {
           "imageDigest": "sha256:d56a04282ebd8946a2231cfb162256335c5ac09c1a0bcae88c112d56c7890f05"
       }
   ],
   "failures": []
}
Deploy of hcp to staging complete, image: 357801675085.dkr.ecr.us-east-1.amazonaws.com/boc-staging-hcp:20160323183016-8b06035
Done. Your build exited with 0.

**Comment by fillup** [comment]
@sriney-boc I just wanted to acknowledge this, I'll do some more testing now myself too

**Comment by fillup** [comment]
@sriney-boc I found the issue was with the regex and the order of using a hyphen in it, moving it to the end seems to work for my image names as well as one formatted like yours. Please let me know if that fixes it.
