### ISSUE TITLE
Support for multi-container task definitions

### ISSUE THREAD

**Issue by shsu** [silinternational/ecs-deploy#30]
The ecs-deploy cli will update both containers to be the same one if the task definitions have multiple docker containers defined.

My best guess: https://github.com/silinternational/ecs-deploy/blob/master/ecs-deploy#L282

**Comment by steevel** [comment]
I was about to patch ecs-proxy with support for this but doing that kind of thing in bash is not my idea of fun. I semi-forked ecs-proxy to https://github.com/steevel/ecs-deploy-multi and rewrote it in python3. It's far from done but I'm currently using it for ci-deployments to QA. Sorry for the shameless plug.

**Comment by shsu** [comment]
It's alright, I decided to write my own simple ruby script to perform this action.

**Comment by fillup** [comment]
Hi @shsu I'm sorry I didn't get to this issue sooner and you had to find a different solution. I just tested this with one of my services where I have two containers in the task definition each using different images and it only updated the one I wanted it to update. Can you give me an example of your use case?

In my use case I have ServiceA which has two containers: ```web``` which uses the image ```silintl/apache2``` and a second container named ```redirect``` running the ```silintl/http-to-https``` image. When I run ```./ecs-deploy -c staging1 -n staging-service-a -i silintl/http-to-https:latest``` it only updates the ```redirect``` container image and leaves the other along. Similarly when I run ```./ecs-deploy -c staging1 -n staging-developer-portal -i silintl/apache2:latest``` it only updates the ```web``` container.

**Comment by shsu** [comment]
That's odd, In my case it overwrote both containers with the same image.

**Comment by fillup** [comment]
I know that was an issue a long time back, but I'm pretty sure that has been fixed for months now.

**Comment by shsu** [comment]
I'll let you know if this issue exists again - Thanks for replying!

**Comment by fillup** [comment]
Sounds good, thanks.
