### ISSUE TITLE
IAM role credentials support?

### ISSUE THREAD

**Issue by rafaelfelix** [silinternational/ecs-deploy#31]
This is actually a feature request. Any plans to support gathering credentials through IAM roles?

BTW, nicely done! Congrats, the script is incredibly useful.

Cheers,

**Comment by fillup** [comment]
Hi @rafaelfelix I believe we have that already although I don't use it personally so I dont know if it is exactly what you're looking for, but see argument ```--aws-instance-profile``` as well as lines 159-169 where there are references to ```$AWS_IAM_ROLE```.

If those don't do what you're looking for let me know and maybe explain a bit more about your use case.

**Comment by rafaelfelix** [comment]
You're right!  Just tested it successfully,  thank you!

**Comment by fillup** [comment]
Great!
