### ISSUE TITLE
Python rewrite

### ISSUE THREAD

**Issue by fillup** [silinternational/ecs-deploy#33]
@steevel - I liked your comment about starting a python rewrite. When we started this we did it in Bash because our initial use case was so basic it just seemed right. However as the popularity of this script has grown and we've received so many PRs, I've really wished it was better suited for unit testing and some automation for that. 

Would you be interested in helping us with the rewrite? I also saw you were doing it in Python 3, but Python 2 is still the default for so most distros right? Could the rewrite be done in 2 but `__future__` imports for forward compatibility too? I'm not much of a python developer myself so I'd love some help with it if you're open to it.

I'm also interested in feedback from more people using this script to know whether they'd appreciate it being in Python as well or perhaps if they are using it because it is bash. If you're using `ecs-deploy` please add comments to let me know what you think.

**Comment by steevel** [comment]
I think this sounds like a really good idea.

I'd love to hear from other people (that are using ecs-deploy) about whether or not they have python3 installed on their machines. The main reason I chose python3 was not because of features but because I think new projects should try to adopt it over python2 to get the ball rolling in the right direction there. I have to problem switching to python2 if that's what the majority wants though.

About testing: YES! That would have caught the regression I introduced in one of my PR's :-)

How do you want to go about doing this?

**Comment by fillup** [comment]
I agree with your intent to be part of the solution in moving forward with versions, and am happy to go that route as well. I'll create a branch for the work and bring you on as a collaborator so you can push directly to it, and then we can use a PR to get it into the mainline to simplify reviews and such. We can probably leave the shell script intact as well since we wont collide with it and it can remain an option for those who prefer it, what do you think?

**Comment by steevel** [comment]
Sounds good to me.

As for keeping the bash-script around, it has to be really clear that it won't have the same functionallity as the python version and that we're keeping it for legacy reasons.

**Comment by fillup** [comment]
Agreed. I'm happy to continue accepting PRs on the bash version if folks want to use it and improve it, but I agree that future efforts can target python where we can put in some better structure, testing, and management.

**Comment by mariomarin** [comment]
@fillup @steevel [docker-osx-dev](https://github.com/brikis98/docker-osx-dev) is written in bash, uses bats for testing and could be used as a reference to improve the modularity of the script.

**Comment by frankV** [comment]
@fillup have you started your Python rewrite? I'd be happy to lend a hand

**Comment by steevel** [comment]
I wish I had some time to dedicate on this at the moment but I really don't (trying to release my new startup). @frankV: You could totally start working on this, there's a lot of features missing in ecs-deploy today that will be tricky (a lot of LOC) to solve in bash. I'll jump on this as soon as I can but probably not until September by the looks of it.

**Comment by frankV** [comment]
@steevel my own work has prevented me from taking lead here, but today I found this... 

https://bitbucket.org/awslabs/amazon-ecs-bitbucket-pipelines-python/src/a7f2ec188250b01474fbbbab4cfa0a4e41d2fd65/ecs_deploy.py?at=master&fileviewer=file-view-default

I'm working on some additions today, hopefully I can hack this apart to begin a base for the Python rewrite.

**Comment by frankV** [comment]
@fillup @steevel we have a first version up (https://github.com/cuttlesoft/ecs-deploy.py). It mimics the behavior of and functionality of this version. Please kindly check it out and provide your feedback.

**Comment by rfroetscher** [comment]
check this out https://github.com/lumoslabs/broadside

**Comment by hamx0r** [comment]
I just found ecs-deploy today and am weighing in as a user, a python developer (nice work @frankV  !), an aspiring Go developer (i see the new branch), and a wheel user (not re-inventer - nice find @rfroetscher ).  Given the age of this Issue, can I assume the other solutions have taken away the need/desire to refactor ecs-deploy into another language?  broadside looks especially cool.

**Comment by fillup** [comment]
@hamx0r at this time we plan to continue to support and maintain `ecs-deploy` as a `bash` script, but we're happy to reference ports from the README. @frankV once I get PR #88 merged in I'll update the readme with a link.

**Comment by zeroasterisk** [comment]
FYI - I have used both the bash and python, both seem functional.

I have a slight preference for the python version, but I don't need to use it... going forward, should I only use the bash or will the python version be maintained? @frankV

**Comment by frankV** [comment]
@zeroasterisk It will be maintained - though I admit it needs some TLC at the moment.

**Comment by fillup** [comment]
At this point if I was to rewrite this I'd do it in Go, but I'm not sure I'll have the time to do that so I've closed this issue.

**Comment by rfroetscher** [comment]
i did post this above, but this does exactly the same stuff and more. https://github.com/lumoslabs/broadside
