### ISSUE TITLE
docker example

### ISSUE THREAD

**Issue by jeremypumphrey** [silinternational/ecs-deploy#36]
I'm not able to follow your docker example. It should have a docker run rather than just the script name right? I've tried versions of the following but all either give me the usage message or complain about not having the credentials and needing "aws configure". I shouldn't need to run aws configure inside a docker if I pass in the key and secret key right? Any help would be appreciated. 

docker run -it --rm silintl/ecs-deploy --aws-access-key KEYHERE --aws-secret-key SECRETHERE --cluster uMatch-Test --region us-east-1 --service-name uMatch-nci-treatment-arm-api-TEST -i matchbox/nci-treatment-arm-api:latest

**Comment by fillup** [comment]
@jeremypumphrey try that again without the ```-it```. That puts Docker into an interactive mode so you can do things like run ```bash``` to get to a command prompt. Otherwise I think you're right, you should be able to do it the way you have it.

In order to keep the key and secret out of history though I use the included ```local.env.dist``` file and put the values in there (but rename the file to ```local.env```) and then use docker-compose to run the container. So then my command line is something like:

```docker-compose run --rm ecsdeploy -c clusterName -s serviceName -i imageName```

**Comment by jeremypumphrey** [comment]
docker run --rm silintl/ecs-deploy --aws-access-key XXX --aws-secret-key XXX --cluster uMatch-Test --region us-east-1 --service-name uMatch-nci-treatment-arm-api-TEST -i matchbox/nci-treatment-arm-api:latest

Using image name: matchbox/nci-treatment-arm-api:latest
Unable to locate credentials. You can configure credentials by running "aws configure".
Current task definition: 
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --task-definition: expected one argument

Error parsing parameter 'cli-input-json': Invalid JSON: No JSON object could be decoded
JSON received: 
New task definition: 
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --task-definition: expected one argument


Didn't change any without the -it. It looks like it either isn't using the passed in keys, or is trying to do something else that depends on the aws config file, which doesn't exist inside the docker container.

**Comment by jeremypumphrey** [comment]
I'm trying to base what commands I use on the image checked into dockerhub, so I'm not following the docker-compose comment. I don't want to build a new image, just use the latest image available. I'm passing the arguments it says are required, but doesn't seem to be working.

**Comment by fillup** [comment]
@jeremypumphrey I just tested the way you're using it and I AM able to duplicate the issue. Apparently somewhere along the way we broke using key/secret via arguments. 

It does work though if you provide them as environment variables to the container via docker run. There are two ways to do this:

Better option: store them in file and load in like:
```docker run --rm --env-file=temp.env silintl/ecs-deploy -c clusterName -n serviceName -i imageName```
The file should be formatted the same as the ```local.env.dist``` file in this repo. 

Second option: pass each one as environment variables to docker run:
```docker run --rm -e AWS_ACCESS_KEY_ID=yourid -e AWS_SECRET_ACCESS_KEY=yoursecret -e AWS_DEFAULT_REGION=yourawsregion silintl/ecs-deploy -c clusterName -n serviceName -i imageName```

If you are going to run this in an environment time and time again, like from your own shell, you can also have these environment variables set in your own shell environment and pass them through to docker like this:
```docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION silintl/ecs-deploy -c clusterName -n serviceName -i imageName```
You just omit the =value portion of each of them.

**Comment by jeremypumphrey** [comment]
Thanks, yes as a workaround this did work for me:

docker run -it --rm -e AWS_ACCESS_KEY_ID=XXX -e AWS_SECRET_ACCESS_KEY=XXX -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy --cluster uMatch-Test --service-name uMatch-nci-treatment-arm-api-TEST -i matchbox/nci-treatment-arm-api:latest
