### ISSUE TITLE
Doesn't replace image version with latest commit

### ISSUE THREAD

**Issue by bkyarger** [silinternational/ecs-deploy#38]
The change to the sed regex has broken ecs-deploy for us.  It doesn't match anything and therefore the same image version is deployed over again.

**Comment by bkyarger** [comment]
Is it possible to get the previous commit deployed as a tag to dockerhub?  Doesn't have to be :latest but just some version that I can use?

**Comment by fillup** [comment]
Wow, really sorry about that @bkyarger. Can you provide an example of an image name that isn't working for you? I tested this with ours where we use a unix timestamp as the tag on the image and it worked fine so I thought it was good to go. I just built and pushed up [silintl/ecs-deploy:5f29db1](https://hub.docker.com/r/silintl/ecs-deploy/tags/) for you built from the previous commit. Let me know what your image name syntax is so we can fix the sed for future builds.

**Comment by bkyarger** [comment]
Here's an example of an image that doesn't match the regex:

143113013094.dkr.ecr.us-east-1.amazonaws.com/republic/rscom-ui-release:REL1_1_2


If you want to send me the replacement `sed` command I can test it out to make sure it replaces the version number in the task.

**Comment by turley** [comment]
I've run into this issue also. I believe it's related to the fact that `sed` behaves differently on different platforms (e.g., GNU vs BSD), especially with regard to escaping. In this case, the parentheses in `(:.*)` need to be escaped in some cases (though they need to *not* be escaped in others).

**Comment by bkyarger** [comment]
We're running on rhel, but I've tested on mac and the (:.*)? doesn't work on either for me with the image example above.

**Comment by fillup** [comment]
Interesting @turley. Are you passing the tag name directly with the image name via the ```-i``` parameter? Or telling it to get the tag name from an environment variable using ```-e```. @bkyarger you're using the Docker image version right?

**Comment by bkyarger** [comment]
I'm using the docker version, but also using the docker compose script from github.

**Comment by turley** [comment]
@fillup - I'm passing the tag with the `-e` option.

**Comment by fillup** [comment]
Okay, I think I got the regex fixed. It is at least working in the several test cases I could come up with from inside the Docker image. @bkyarger and @turley can you guys check out https://github.com/silinternational/ecs-deploy/tree/sed-fix and let me know if it works for you. If so I'll merge it into master. Sorry again for the hassle.

**Comment by bkyarger** [comment]
I will check it in an hour or so. Thanks!

**Comment by turley** [comment]
@fillup From what I can tell, the `sed-fix` branch assumes that the current image in the task definition is tagged. I like anchoring to the `:` (so it doesn't match images in the definition that could have names that are suffixed with something else), but it should still probably be optional. Since the parentheses seem to be a problem for compatibility, maybe it could be run through 2 separate substitutions... What about something like this:
```
...
  | sed -e "s|\"image\": *\"${imageWithoutTag}:[^\"]+\"|\"image\": \"${useImage}\"|g" \
  | sed -e "s|\"image\": *\"${imageWithoutTag}\"|\"image\": \"${useImage}\"|g"
...
```

**Comment by fillup** [comment]
@turley I'm good with something like that. Using ```[^\"]+``` did not work for me though. I had to change to:

```
        | sed -e "s|\"image\": *\"${imageWithoutTag}:.*\"|\"image\": \"${useImage}\"|g" \
        | sed -e "s|\"image\": *\"${imageWithoutTag}\"|\"image\": \"${useImage}\"|g" \
```

**Comment by turley** [comment]
@fillup I think that should work (for me at least). As long as the aws command returns the the key/value pair on its own line, the greedy `.*` shouldn't cause a problem.

**Comment by fillup** [comment]
It should only run up to the next ```"``` though right?

**Comment by bkyarger** [comment]
I have confirmed that this works for my image values.  Thanks for the quick turnaround!

**Comment by bkyarger** [comment]
One thing that might be nice would be publishing tagged versions to dockerhub.  That way I could target something other than :latest in my deployment process.

**Comment by fillup** [comment]
@bkyarger thanks for confirming the fix. I agree, I've been intending to do that and just haven't, but I'll get that going.

**Comment by fillup** [comment]
I updated docker hub build settings to build tagged versions too and pushed a new tag for 2.3.1 so it is building now. 

Thanks!
