### ISSUE TITLE
A client error occured when calling the DescribeTasks operation: taskId longer than 36.

### ISSUE THREAD

**Issue by pni-bwhitlock** [silinternational/ecs-deploy#43]
A client error (InvalidParameterException) occurred when calling the DescribeTasks operation: taskId longer than 36.
xargs: /c/Amazon/AWSCLI/aws: exited with status 255; aborting

I'm getting this one on windows.

![capture](https://cloud.githubusercontent.com/assets/19596336/16206570/df55a4e8-36dd-11e6-90dc-428d5210e73e.PNG)

**Comment by fillup** [comment]
Hi @pni-bwhitlock, that sounds like an error coming from the AWS CLI. Do you have the latest version of the AWS CLI installed? I also see you're on Windows. Have you tried running the Docker image version of the script to run it on Linux rather than Windows?

**Comment by pni-bwhitlock** [comment]
@fillup  Thanks for the response. I ended up running the deploy inside the docker container and everything works great. Thank for a great package! An amazing timesaver!

**Comment by fillup** [comment]
@pni-bwhitlock that is great, thanks for letting us know! Also glad to hear the script is helpful for you too :-)
