### ISSUE TITLE
AWS IAM Policy Configuration, needs updating

### ISSUE THREAD

**Issue by jeremypumphrey** [silinternational/ecs-deploy#44]
Great service, thanks for sharing. I just created a custom IAM policy to run this (after using admin for  a few weeks). There seems to have been a layout change to IAM policies since you posted, so wanted to let you know so you could update your example on DockerHub. What you had converted to the new layout looks like this:
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecs:DeregisterTaskDefinition",
                "ecs:DescribeServices",
                "ecs:DescribeTaskDefinition",
                "ecs:DescribeTasks",
                "ecs:ListTasks",
                "ecs:RegisterTaskDefinition",
                "ecs:StartTask",
                "ecs:StopTask",
                "ecs:UpdateService"
            ],
            "Resource": "*"
        }
    ]
}
`

**Comment by fillup** [comment]
Thanks @jeremypumphrey. That looks like the same policy without the Sid attribute, which is probably a good thing since I assume that is expected to be a unique value. I'll update the readme.
