### ISSUE TITLE
Use aws-cli config and credential files

### ISSUE THREAD

**Issue by frankV** [silinternational/ecs-deploy#45]
The aws-cli creates two files in a user's home directory under `~/.aws`:
 1. `credentials` (contains the AWS_ACCESS_KEY and the AWS_SECRET_ACCESS_KEY)
 2. `config.json` (contains the default region)

It would be nice if ecs-deploy used the values in these files as a fallback to the env vars or cli arguments.

**Comment by fillup** [comment]
Hi @frankV, it looks like PR #47 is what you're asking for right? Can you check it out and see if it resolves what you're looking for? I generally only use ecs-deploy from a docker container so I provide the values via env vars every time, but would be happy to make it more useful for you to use directly. My only concern about that PR is that by removing the check for the env vars which allows aws-cli to fall back to the files is then there is not the friendly error when using ecs-deploy without either.

**Comment by frankV** [comment]
Maybe #47 just needs to implement the better error handling?

**Comment by fillup** [comment]
I just tested out #47 and I think the change to error handling is probably fine. It is not as clear but I've added a Troubleshooting section to the README that will hopefully help. You should be all set go to with version tag 2.4.0 now.
