### ISSUE TITLE
HomeBrew formula

### ISSUE THREAD

**Issue by tomhughesnice** [silinternational/ecs-deploy#46]
Hi,

I was wondering if you had considered creating a Homebrew Formulae for this tool? 

Good work btw, makes ECS deployments a breeze.

Thanks,

Tom

**Comment by fillup** [comment]
Hi @tomhughesnice, I've never done that before but am more than happy to include any distribution channels that would be helpful. Is that something you can contribute via pull request? Right now I have Docker Hub and Composer distribution setup but am also interested in PIP, NPM, others?

**Comment by fillup** [comment]
Hi @tomhughesnice I found a nice article tonight, http://formalfriday.club/2015/01/05/creating-your-own-homebrew-tap-and-formula.html, and setting up a new Tap and Formula were quite easy. Give it a shot and let me know if it works for you:

```
brew tap silinternational/tap
brew install ecs-deploy
```

**Comment by xgt001** [comment]
@fillup ☝️ worked pretty well for me

**Comment by fillup** [comment]
Great, I'm going to roll another release in a minute that fixes the taskRole stuff so I'll update the formula after that for the new version too
