### ISSUE TITLE
ecs-deploy removes per-task IAM roles in task definitions

### ISSUE THREAD

**Issue by statusfailed** [silinternational/ecs-deploy#48]
AWS added support for per-task IAM roles on [2016-07-13](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html). This role is exposed in the Task Definition JSON via the field `taskRoleArn`. **ecs-deploy** currently omits this field when updating a task definition, effectively removing it. 

The reason is line 304:

```
| jq '.taskDefinition|{ family: .family, volumes: .volumes, containerDefinitions: .containerDefinitions}' )
```

I've fixed this by simply adding the new `taskRoleArn` field:

```
| jq '.taskDefinition|{ family: .family, volumes: .volumes, containerDefinitions: .containerDefinitions, taskRoleArn: .taskRoleArn}' )
```

However, I'm not sure if this will cause problems for users on older versions of the AWS CLI.

**Comment by fillup** [comment]
@statusfailed thank you for opening this issue. I just tested this locally, and I have not updated my aws-cli for a little while and I get an error:

```
$ ./ecs-deploy -c staging1 -n doorman-api -i imagename
Using image name: imagename
Current task definition: taskdef:111

Parameter validation failed:
Unknown parameter in input: "taskRoleArn", must be one of: family, containerDefinitions, volumes
New task definition: 
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --task-definition: expected one argument
✘-2 ~/code/docker/ecs-deploy [develop|✚ 1] 
10:10 $ aws --version
aws-cli/1.10.46 Python/2.7.12 Linux/4.4.0-31-generic botocore/1.4.36
```

I upgraded AWS CLI to version ```1.10.47``` and I get a different error, but it looks like it works:

```
$ ./ecs-deploy -c staging1 -n doorman-api -i imagename
Using image name: imagename
Current task definition: taskdef:111

Parameter validation failed:
Invalid type for parameter taskRoleArn, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
New task definition: 
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --task-definition: expected one argument
$ aws --version
aws-cli/1.10.47 Python/2.7.12 Linux/4.4.0-31-generic botocore/1.4.37
```

For those who do not use per-task IAM roals, do you know if there is a safe way to include this? Seems like we may need it to be conditional based on presence in current task definition?

**Comment by triplesek** [comment]
I too am affected by this.

**Comment by fillup** [comment]
@triplesek by affected do you mean you are using per task roles and having issues with ecs-deploy now because it doesn't support that attribute yet?

**Comment by triplesek** [comment]
yes

**Comment by seanadkinson** [comment]
Also need my task role to be persisted across updates.  Will try the fix provided by the OP.

**Comment by fillup** [comment]
Do we have any solutions for supporting the new task roles but not requiring them?

**Comment by triplesek** [comment]
Is there a downside to adding the `taskRoleArn` field if it doesn't already exist? 
...at least when building the Docker image, don't you get a reasonably up-to-date `awscli`?

**Comment by fillup** [comment]
@triplesek sorry for delays. Does the API support an empty/null value for taskRoleArn? I haven't looked at it yet via the CLI but can try to do so in the next few days. I would think so long as we can keep the same value whether there is one or it's empty then we can include it.

**Comment by fillup** [comment]
I believe I came up with a solution that resolves this and gets us ready for future additions of conditional options like this. Please check out the `feature/conditionalOptions` branch and see if that works for you. I'll wait a little bit before merging it in and releasing it in case you find issues with it.

**Comment by seanadkinson** [comment]
@fillup Great, will plug in that code and test it out for my scenario.  Thanks.

**Comment by fillup** [comment]
I assume not hearing back any more that this is working for you, let me know and reopen if not though.
