### ISSUE TITLE
Blue green deployment doesn't seem to be working for me 

### ISSUE THREAD

**Issue by malawson** [silinternational/ecs-deploy#68]
hi, i just tried this tool on a ECS cluster with the following specs 
Registered Container Instances 	:	4
Pending tasks 	:	0
Running tasks 	:	2

So i do have enough capacity in my cluster for blue/green deployments. Yet when i run this the new task is never run inside the ECS cluster, not quite sure what i may be doing wrong. 
./ecs-deploy -v -c mup-social-ECSCluster-1G965XTDFBLO1 -n mup-social-Service-U2QPXOXIJ9FL -i 414367886899.dkr.ecr.us-east-1.amazonaws.com/mup/mup-social:icorbett-snapshot -t 1200 -m 50 -M 100 -D 2 

As far as verbose mode here is what i get: 

[ecs-deploy.log.txt](https://github.com/silinternational/ecs-deploy/files/486312/ecs-deploy.log.txt)

**Comment by fillup** [comment]
Which branch/tag are you using?

**Comment by malawson** [comment]
i am actually on the "develop" branch

**Comment by malawson** [comment]
and i think tag 2.6.0

**Comment by fillup** [comment]
It looks like it worked, I see:

`Current task definition: arn:aws:ecs:us-east-1:414367886899:task-definition/mup-social-TaskDefinition-VM31RTN9TZCF:2`

and further down:

`New task definition: arn:aws:ecs:us-east-1:414367886899:task-definition/mup-social-TaskDefinition-VM31RTN9TZCF:3`

You gave it a long timeout for ECS to launch the new tasks, but the attachment output cuts out so I don't see if it eventually finished or not. When you check the running tasks in ECS do you see it running version 3 of the task definition?

**Comment by malawson** [comment]
it's actually not completing i just ran another one with -t 600 and let it timeout after 10mins. i am attaching the verbose output. 

[ecs-deploy.log.txt](https://github.com/silinternational/ecs-deploy/files/486452/ecs-deploy.log.txt)

**Comment by fillup** [comment]
Hmmm, check the deployments tab when viewing your service in ECS and see if there are any helpful errors there. A common one is not having enough resources available to place the task and therefore it fails. Also in ECS check the ECS Instances tab for your cluster and see if the agent status is `false` for any of your instances. Amazon has improved the stability of the agent over time, but occasionally it fails and cannot recover and you just have to replace the EC2 instance (as far as I can figure out from troubleshooting anyway). If the agent status is false, replace the EC2 instances and see if that helps. If it is not false maybe we can get an a Hangout or something to look at it together. From the output you sent it clearly creates the new task definition and updates the service to use it. You also have minimum healthy percent of 50% so ECS should be able to kill one of the previous versions to launch the new one. Another potential problem is if the new one is launched but fails/dies/exits and never becomes healthy then ECS will not kill the second original one to launch a new one. So if you check your service and see it is configured to use the new task definition, then under the Tasks tab click on "Stopped" to see stopped containers and see if the new one is just failing to stay running.

**Comment by malawson** [comment]
Thanks for all this info, it does help in being able to track deployments more closely in ECS. I think the issue i was having is that i kept deploying the same image (&tag) over and over and ECS doesn't seem to be updating the cluster with the new task definition if the image:tag is the same as the current. Changing the tag name used to construct the task definition triggers the rolling update with your script. However i also intend to open a ticket with AWS to confirm that this is a requirement for the `aws ecs update-service` command. Let me kow if you have any other suggestions. Thanks for your help.

**Comment by fillup** [comment]
That is surprising actually. For a while we were just updating our task definitions with exactly the same image name and tag and it definitely deployed the updated task definition. In fact that is how I test `ecs-deploy` often is just updating a service to use the exact same image/tag and it works every time. Since a new task definition is created I'm not sure ECS is aware that is really the same image/tag running and therefore not deploy the update. I'll go ahead and close this issue for now but please re-open if you think there is still an issue with `ecs-deploy` that we can address.

**Comment by malawson** [comment]
Actually i tested further and it does complete/work with the same or a different image, it just takes a while sometimes 30 mins vs. the default 90 seconds status check. But among other things the timing depends on the environment being deployed of course. Thanks.

**Comment by robbiet480** [comment]
I am also experiencing the same issue now it seems. Repeatedly deploying `robbiet480/my-test-app:latest` sometimes will not update the image on the ECS instances. If I SSH into one and run a `docker pull` on it it does update.

**Comment by robbiet480** [comment]
@malawson Did you end up opening a ticket with AWS? I can't find any documentation or resources about this behavior.

**Comment by malawson** [comment]
@robbiet480 i didn't open a ticket in the end because the tool is now working on most attempts. I think i will keep using it and the next time the `aws ecs service-update` command fails to update the service again i will email them about it.
