### ISSUE TITLE
InvalidSignatureException when calling the DescribeServices operation

### ISSUE THREAD

**Issue by asotirov** [silinternational/ecs-deploy#69]
I run it like this.

`$ docker run -it --rm -e AWS_ACCESS_KEY_ID=XXX -e AWS_SECRET_ACCESS_KEY=XXX -e  AWS_DEFAULT_REGION=eu-west-1 silintl/ecs-deploy --cluster "batman-cluster" --service-name "batman-service" -i "iii:feature/xxx"`

Using image name: iii:feature/xxx

An error occurred (InvalidSignatureException) when calling the DescribeServices operation: Signature expired: 20160925T124307Z is now earlier than 20160925T125643Z (20160925T13014Z - 5 min.)
Current task definition:
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --task-definition: expected one argument

Error parsing parameter 'cli-input-json': Invalid JSON: No JSON object could be decoded
JSON received:
New task definition:
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --task-definition: expected one argument

`System information`

From Windows 7

`docker version`

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

`docker-machine version`
docker-machine.exe version 0.6.0, build e27fb87

**Comment by fillup** [comment]
Interesting. It sounds to me like there is an issue with the time on your Windows machine. Windows is notorious for not knowing how to keep time well. We run some APIs internally that use a time based signature authentication method and we constantly have issues with Windows clients not keeping time. 

I believe by default Docker is getting time time from your Windows machine, via the Docker Machine VirtualBox VM. One option could be to get into the Docker host VM (`docker-machine ssh`) and install and run ntpd in it to get it to sync time with an internet time service. Another option could be to check out this utility from Microsoft: https://technet.microsoft.com/en-us/library/w32tm.aspx. However be aware that even Microsoft says:

> The Windows Time service is not a full-featured NTP solution that meets time-sensitive application needs, and it is not supported by Microsoft as such. For more information, see article [939322](http://go.microsoft.com/fwlink/?LinkID=179459) in the Microsoft Knowledge Base.

You may also want to check out this Server Fault post for more information about Hyper-V and time issues: http://serverfault.com/questions/196716/w32tm-returning-inconsistent-results

Let me know if implementing any time-sync utilities resolves this for you as I'd like to be aware of the solution.

**Comment by asotirov** [comment]
I restarted docker-machine and the thing seems to WORK. 

Have to say - nice job! - now that I've tested it. 

Thank you for your contribution!

btw, https://technet.microsoft.com/en-us/library/w32tm.aspx doesn't seem to work.

If I have the same issue again, I will reopen this :)
