### ISSUE TITLE
Script reports failure if task count is 0.

### ISSUE THREAD

**Issue by brycereitano** [silinternational/ecs-deploy#7]
When running the script on a service that has a task count of 0, it will fail while trying to see if the task has started. This has occurred once while I was debugging my setup and disabled a portion of the services and some new code was deployed. The only issue here is it returns a non-zero response which causes the CI I'm using to stop in its tracks. The script should have a graceful way of handling services that won't be instantiated right away.

**Comment by fillup** [comment]
@brycereitano do I understand correctly that you have a service defined to run zero tasks, and when calling ecs-deploy on that service it throws an error?

**Comment by brycereitano** [comment]
@fillup It will timeout when attempting to find the new task definition running.
