### ISSUE TITLE
Double slash in image name

### ISSUE THREAD

**Issue by asotirov** [silinternational/ecs-deploy#70]
#71 
Command:
/var/www/ecs-deploy.sh --cluster "batman-cluster" --service-name "batman-service" -i asotirov/tickey-serverside:r-batman-1.94

Result:
Using image name: asotirov*`//`*tickey-serverside:r-batman-1.94
Current task definition: arn:aws:ecs:eu-west-1:267034406528:task-definition/batman-task:24
New task definition: arn:aws:ecs:eu-west-1:267034406528:task-definition/batman-task:25

**Comment by elfenars** [comment]
Also have this issue, broke all my deployments...Please merge!!

**Comment by waziers** [comment]
Any update on merging this? This has also broken my deployments.

**Comment by fillup** [comment]
Sorry for the delay, yes I'll check this out and merge it in today.
