### ISSUE TITLE
Replace tag for images

### ISSUE THREAD

**Issue by Forever-Young** [silinternational/ecs-deploy#72]
I wrote a script to replace tags for all containers in the task definition, based on your script, maybe add parameter --tag or something?

https://gist.github.com/Forever-Young/e939d9cc41bc7a105cdcf8cd7ab9d714

Main part is

```
NEW_CONTAINER_DEFINITIONS=$(echo "$TASK_DEFINITION" | jq --arg NEW_TAG $NEW_TAG 'def replace_tag: if . | test("[a-zA-Z0-9.]+/[a-zA-Z0-9]+:[a-zA-Z0-9]+") then sub("(?<s>[a-zA-Z0-9.]+/[a-zA-Z0-9]+:)[a-zA-Z0-9]+"; "\(.s)" + $NEW_TAG) else . end ; .containerDefinitions | [.[] | .+{image: .image | replace_tag}]')
```

I think test part needs an improvement, I don't check for docker-hub/private images for example

**Comment by fillup** [comment]
Hi @Forever-Young I just received a PR for what I think is the same thing you're looking for. Can you check out #79 and see if it does what you need?

**Comment by Forever-Young** [comment]
Seems to be the same idea, but different implementation
