### ISSUE TITLE
Regression bug replacing image name of all containers in service

### ISSUE THREAD

**Issue by fillup** [silinternational/ecs-deploy#73]
@gregwebs your change to use jq instead of sed for updating image names appears to have broken services that have multiple containers using different names. I should have tested for it but forgot and now we have a regression bug. Can you fix this so that it only updates containers that match the image name given without the tag like it did before?

See commit cc75ef18a1fbaf595476c97e3ef0720d20c5f336

**Comment by gregwebs** [comment]
ahh, dang, sorry, I need to watch out for this since I use lots of ECS clusters and only have one service (with 1 container) running in the ECS cluster. Can you just revert the commit for now?

**Comment by gregwebs** [comment]
I will send a PR with it reverted right now

**Comment by gregwebs** [comment]
https://github.com/silinternational/ecs-deploy/pull/74

**Comment by fillup** [comment]
Thanks for the fix!
