### ISSUE TITLE
Task Role not duplicated

### ISSUE THREAD

**Issue by mirague** [silinternational/ecs-deploy#76]
I have a specific IAM role for my Task Definitions. This one is not duplicated after running `ecs-deploy`, which means the service does not run with the required permissions. Is there a flag we can pass in to assign a Task Definition IAM role? Or perhaps certain rights are required to assign this role?

Using `awscli: 1.11.5` and the latest `ecs-deploy` from `develop`

**Edit:** I see this has been discussed in #48, but it seems the solution never made it into `ecs-deploy`. 

**Edit 2:** I see there's been a merged PR #64, #67 aiming to address this issue. For me this is not working, however. Any pointers?

**Comment by gerar2** [comment]
This was working properly for us and stop working recently. It must be some recent commit

**Comment by mirague** [comment]
Any idea what could have "undone" this improvement @fillup ?

**Comment by mirague** [comment]
We found that `taskRoleArn` isn't even returned in the `aws ecs describe-task-definition` command. It's supposed to, according to the [docs](http://docs.aws.amazon.com/cli/latest/reference/ecs/describe-task-definition.html).

**Comment by mirague** [comment]
Alright, solved this issue and opened up a PR (#76).

Somehow the returned old definition was filtered out and reconstructed before the logic of including the `taskRoleArn` was even included. I believe this filter was placed back/never removed by accident.

**Comment by fillup** [comment]
PR #76 merged in
