### ISSUE TITLE
Error ProfileNotFound with a command without profile

### ISSUE THREAD

**Issue by Godefroy** [silinternational/ecs-deploy#80]
Hi,

I'm trying to use ecs-deploy with a simple config but I get this error:

![capture](https://cloud.githubusercontent.com/assets/148421/20014449/4a3919da-a2b7-11e6-817f-fc3d87357a29.png)

AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION are defined and working (I'm using awscli for other stuff).

Do you have an idea?

**Comment by Godefroy** [comment]
Problem solved, it wasn't obvious but it just a user pemission issue.

**Comment by fillup** [comment]
Ahh, glad it was easy, thanks for letting us know for future awareness.
