### ISSUE TITLE
unbound variable

### ISSUE THREAD

**Issue by flimzy** [silinternational/ecs-deploy#81]
I was calling ecs-deploy incorrectly, as such:

    ./ecs-deploy -r "$AWS_DEFAULT_REGION" -k "$AWS_ACCESS_KEY_ID" -s "$AWS_SECRET_ACCESS_KEY" -c $CLUSTER -n $NAME -i $IMAGE -e $TAG

Note in particular, `-e $TAG` as opposed to `-e TAG`.

And it resulted in the following error:

> ./ecs-deploy: line 262: !TAGVAR: unbound variable

A bad variable name passed to -e should probably generate a more friendly error message.

**Comment by fillup** [comment]
I addressed a bunch of these errors in todays release so I'll close this for now until a new one pops up.
