### ISSUE TITLE
package ecs-deploy

### ISSUE THREAD

**Issue by myoung34** [silinternational/ecs-deploy#82]
Right now I install it via an ugly `wget`. would be nice if it were in brew or pip

**Comment by fillup** [comment]
It is available in brew, I suppose I should get that added to readme so folks actually know about it :-)

Don't have my mac with me right now but I believe you just need to:

```
$ brew tap silinternational/tap
$ brew install ecs-deploy
```

**Comment by myoung34** [comment]
What about ubuntu/yum ? Any plans or thoughts? Right now this repo is my go-to for deploying.

**Comment by fillup** [comment]
@myoung34 I'd love to support as many package management options as are available. You want to submit a PR to add whatever is needed for apt/yum? I've used [jordansissel/fpm](https://github.com/jordansissel/fpm) in the past but never published to a public apt/yum repo host. I'd also be interested in pip.

**Comment by boskiv** [comment]
I have successfully installed it with linuxbrew on ubuntu. Thanks @fillup.

**Comment by HughP** [comment]
@fillup I should give you a hug for making an SIL Tap...
