### ISSUE TITLE
Replace tag for multiple container definitions

### ISSUE THREAD

**Issue by vincentkwok** [silinternational/ecs-deploy#84]
Right now, it only replaces the first container definition. For those having same tag container group (i.e. it shares the same tag name), it should be replace as well.

**Comment by fillup** [comment]
@vincentkwok can you look at PR #94 and see if that is what you are looking for. It replaces the tag for all containers regardless of the image name. So for multi-container definitions where each container shares a tag name this can update them all.

**Comment by vincentkwok** [comment]
LGTM. thanks at all

**Comment by genexp** [comment]
Very nice.  We're looking forward to this too.

**Comment by genexp** [comment]
@fillup Can we merge this by chance? Looking to get the new version from PIP!

**Comment by devon-sil** [comment]
PR #94 has already been merged in.  Closing.
