### ISSUE TITLE
env variables

### ISSUE THREAD

**Issue by tcrall** [silinternational/ecs-deploy#92]
Is there a way with this script to set the value of env variables within the container you're deploying?

**Comment by apurvis** [comment]
https://github.com/lumoslabs/broadside

**Comment by ebertti** [comment]
I have the same issue.

**Comment by fillup** [comment]
@tcrall are you asking if when updating the service and creating a new task definition if it can update values of existing environment variables or inject new ones? And would you want them set for all containers in the definition or a specific one?

**Comment by tcrall** [comment]
@fillup actually in the end it turned out that setting the env variables in the service was all I really needed for my use case.

**Comment by fillup** [comment]
Oh ok great, well I'll close this one for now then.

**Comment by ebertti** [comment]
@fillup I need exact what you say:

> updating the service and creating a new task definition if it can update values of existing environment variables or inject new ones

Have some way to do this using your script in task definition like this script does?

https://github.com/fabfuel/ecs-deploy#adjust-multiple-environment-variables

**Comment by fillup** [comment]
Hi @ebertti I'd be open to enhancements like that, but I don't think I'll have time or priority to add them. If you'd like to work on it and submit a PR I'm happy to consider it.

**Comment by ebertti** [comment]
I fix it using `ARGS` and `--build-args` on build of docker image.

😄
