### ISSUE TITLE
ECS deploy script

### ISSUE THREAD

**Issue by jmk4791** [silinternational/ecs-deploy#93]
Hi All,

Do you guys know how do we pull the latest docker image with constant image tag from private repo into aws ECS without modifying image tag in the docker

Because every time I get cached images only from local via ECS agent. I couldn't get able to get latest image with the same tag from private repository

 I configured multiple applications in aws ECS cluster, so whenever Dev updated image/snapshot in a private repo I need to get the latest image in aws cluster 

Because I don't want to use the old image when we got updated image in private repo

Because I created task definition in aws cluster and we are getting the cached image only from ECS agent

**Comment by apurvis** [comment]
we haven't had a problem with this using https://github.com/lumoslabs/broadside

**Comment by fillup** [comment]
@jmk4791 I've not had that problem myself, my experience with ECS is anytime you stop a task, when it starts a new one it pulls the latest image. If you're not getting the latest image for that tag then you definitely have a caching issue somewhere, but whether it is on the ECS host or your registry I'm not sure. If from your own computer you do a `docker pull` for the image do you get the latest version or a previous one? Where are you hosting the private registry? Are you using private Docker Hub repos, Amazon ECR, or hosting your own? 

If I can offer advice or suggestions I'm happy to, but I don't believe this is related to `ecs-deploy` and you may eventually need to get in contact with Amazon.
