### ISSUE TITLE
Wait for service steady state

### ISSUE THREAD

**Issue by danpaz** [silinternational/ecs-deploy#95]
Have you all looked into extending the deploy command to wait for the service to reach "steady state"? Currently, after ecs-deploy exits successfully I can't tell if the updated service was able to place tasks successfully. 

As a stop gap we have been watching the event logs that come out of the aws ecs describe-services command. E.g.

```
watch "aws ecs describe-services --region us-east-1 --cluster staging --services staging-sd-neodarwin --output text --query 'services[0].events[0:5]'"
```

And waiting for a set of messages that look like this, indicating the service is done updating:

```
2017-03-31T14:17:26.154000-04:00        e4b61534-0b90-4b1c-b46e-2ae3625b8018    (service staging-sd-neodarwin) has reached a steady state.
2017-03-31T14:17:15.851000-04:00        95f28e76-2373-4dee-aae2-852d7155ce59    (service staging-sd-neodarwin) has stopped 1 running tasks: (task a1bf1b06-edea-4492-a431-a28b49a362fe).
2017-03-31T14:17:01.962000-04:00        6a51b1d0-1c52-481f-a9d6-eb5e43b8aa04    (service staging-sd-neodarwin) has begun draining connections on 1 tasks.
...
``` 

Would it make sense to add something like this to ecs-deploy? I can make a PR to try this idea out.

Thanks for creating such a great script!

**Comment by fillup** [comment]
#66 was intended to watch for the deployment to succeed or rollback the update to service if it does not work, but when I tested it did not work correctly. Would you be interested in reviewing #66 and helping update it to work with the updated code base for `ecs-deploy`?

**Comment by danpaz** [comment]
Sure I'll give that a try. I like the idea of checking the number of active deployments, though I still think the event logs are useful to monitor what's going on while the service updates. Maybe a combination of the two approaches could work well.
