### ISSUE TITLE
"TASK_DEFINITION_ARN: unbound variable" when using with task definition "-d" option

### ISSUE THREAD

**Issue by bfolkens** [silinternational/ecs-deploy#98]
When using the -d or --task-definition option, an error is produced:

`/ecs-deploy: line 464: TASK_DEFINITION_ARN: unbound variable`

It seems as though the TASK_DEFINITION_ARN is not getting set since SERVICE is false (as it should be), though that branch of code is what is responsible for setting TASK_DEFINITION_ARN.

**Comment by mnc** [comment]
I'm facing the same error like below log.

```
/usr/local/bin/ecs-deploy: line 567: TASK_DEFINITION_ARN: unbound variable
```

Could you merge this [PR](https://github.com/silinternational/ecs-deploy/pull/99)?
I'll try to fix it if there is any problem.

**Comment by thomasbiddle** [comment]
Also hitting this issue; looks like I'll just have to patch my own copy

**Comment by fillup** [comment]
@thomasbiddle #99 also includes some new functionality so I can't just merge in the fix for the unbound variable. If you want to put it in as a new PR I'll be happy to review and merge it in.

**Comment by devon-sil** [comment]
#118 mentions fixing "TASK_DEFINITION_ARN: unbound variable"
